name: ArgoCD Lua Health Check Tests

on:
  push:
    branches: [ master, main ]
    paths:
      - 'resource_customizations/**'
      - 'util/lua/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'resource_customizations/**'
      - 'util/lua/**'
  workflow_dispatch:

jobs:
  test-lua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.4'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run Lua Unit Tests
        run: go test -v ./util/lua/...
